#!/usr/bin/env python3
from __future__ import annotations

import urllib.request
from pathlib import Path


BLACKMATRIX_GLOBAL_URL = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Global/Global_All_No_Resolve.list"
REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = REPO_ROOT / "Global.list"

GLOBAL_EXTENSION_RULES = """\
DOMAIN-SUFFIX,1byte.io
DOMAIN-SUFFIX,ad.gt
DOMAIN-SUFFIX,1rx.io
DOMAIN-SUFFIX,1stream.icu
DOMAIN-SUFFIX,3lift.com
DOMAIN-SUFFIX,4dex.io
DOMAIN-SUFFIX,6sense.com
DOMAIN-SUFFIX,33across.com
DOMAIN-SUFFIX,35pg.com
DOMAIN-SUFFIX,360yield.com
DOMAIN-SUFFIX,22220.xyz
DOMAIN-SUFFIX,303101.xyz
DOMAIN-SUFFIX,a-mo.net
DOMAIN-SUFFIX,a-mx.com
DOMAIN-SUFFIX,a47b.com
DOMAIN-SUFFIX,aaccy.com
DOMAIN-SUFFIX,aait.io
DOMAIN-SUFFIX,aawsat.com
DOMAIN-SUFFIX,aaxads.com
DOMAIN-SUFFIX,abcsinsights.com
DOMAIN-SUFFIX,activemetering.com
DOMAIN-SUFFIX,ad-delivery.net
DOMAIN-SUFFIX,ad-score.com
DOMAIN-SUFFIX,adentifi.com
DOMAIN-SUFFIX,adform.net
DOMAIN-SUFFIX,adition.com
DOMAIN-SUFFIX,adjust.com
DOMAIN-SUFFIX,adjust.net.in
DOMAIN-SUFFIX,adkernel.com
DOMAIN-SUFFIX,adlightning.com
DOMAIN-SUFFIX,adlooxtracking.com
DOMAIN-SUFFIX,admanmedia.com
DOMAIN-SUFFIX,admixer.net
DOMAIN-SUFFIX,adnxs-simple.com
DOMAIN-SUFFIX,adnxs.com
DOMAIN-SUFFIX,adoberesources.net
DOMAIN-SUFFIX,adotmob.com
DOMAIN-SUFFIX,adpartner.pro
DOMAIN-SUFFIX,adroll.com
DOMAIN-SUFFIX,adrta.com
DOMAIN-SUFFIX,adsafeprotected.com
DOMAIN-SUFFIX,adsappier.com
DOMAIN-SUFFIX,adsrvr.org
DOMAIN-SUFFIX,adtelligent.com
DOMAIN-SUFFIX,adthrive.com
DOMAIN-SUFFIX,advertising.com
DOMAIN-SUFFIX,advf.app
DOMAIN-SUFFIX,agkn.com
DOMAIN-SUFFIX,ah3hd.top
DOMAIN-SUFFIX,akile.io
DOMAIN-SUFFIX,algolia.net
DOMAIN-SUFFIX,anaudience.com
DOMAIN-SUFFIX,andbeyond.media
DOMAIN-SUFFIX,aniview.com
DOMAIN-SUFFIX,aoyozhuji.com
DOMAIN-SUFFIX,apernet.io
DOMAIN-SUFFIX,apiip.net
DOMAIN-SUFFIX,app-us1.com
DOMAIN-SUFFIX,apphousekitchen.com
DOMAIN-SUFFIX,appier.net
DOMAIN-SUFFIX,appiersig.com
DOMAIN-SUFFIX,appinn.net
DOMAIN-SUFFIX,apple-studies.com
DOMAIN-SUFFIX,applemediaservices.com
DOMAIN-SUFFIX,appsflyer.com
DOMAIN-SUFFIX,aralego.com
DOMAIN-SUFFIX,aralego.net
DOMAIN-SUFFIX,arstechnica.com
DOMAIN-SUFFIX,arstechnica.net
DOMAIN-SUFFIX,ax1x.com
DOMAIN-SUFFIX,axis-marketplace.com
DOMAIN-SUFFIX,b-cdn.net
DOMAIN-SUFFIX,bdustatic.com
DOMAIN-SUFFIX,betrad.com
DOMAIN-SUFFIX,betweendigital.com
DOMAIN-SUFFIX,bfmio.com
DOMAIN-SUFFIX,bidmaster360.com
DOMAIN-SUFFIX,bidswitch.net
DOMAIN-SUFFIX,bigdata.icu
DOMAIN-SUFFIX,bmp.ovh
DOMAIN-SUFFIX,boccc.co
DOMAIN-SUFFIX,bookacampa.com
DOMAIN-SUFFIX,brainlyads.com
DOMAIN-SUFFIX,branch.io
DOMAIN-SUFFIX,brandmetrics.com
DOMAIN-SUFFIX,braveglobal.tv
DOMAIN-SUFFIX,braze.com
DOMAIN-SUFFIX,browser-intake-datadoghq.com
DOMAIN-SUFFIX,btloader.com
DOMAIN-SUFFIX,buff.ly
DOMAIN-SUFFIX,bugsnag.com
DOMAIN-SUFFIX,buysellads.net
DOMAIN-SUFFIX,bwg.net
DOMAIN-SUFFIX,bwhstats.com
DOMAIN-SUFFIX,bytevirt.com
DOMAIN-SUFFIX,cacafly.net
DOMAIN-SUFFIX,casalemedia.com
DOMAIN-SUFFIX,cdn.optable.co
DOMAIN-SUFFIX,cdn.taboola.com
DOMAIN-SUFFIX,cedexis-test.com
DOMAIN-SUFFIX,cellrebel.com
DOMAIN-SUFFIX,celtra.io
DOMAIN-SUFFIX,cfcloud.life
DOMAIN-SUFFIX,chartbeat.com
DOMAIN-SUFFIX,chartbeat.net
DOMAIN-SUFFIX,chatway.app
DOMAIN-SUFFIX,check.place
DOMAIN-SUFFIX,chinafactcheck.com
DOMAIN-SUFFIX,chng.it
DOMAIN-SUFFIX,clarity.ms
DOMAIN-SUFFIX,clarium.io
DOMAIN-SUFFIX,clean.gg
DOMAIN-SUFFIX,clickcertain.com
DOMAIN-SUFFIX,cluep.com
DOMAIN-SUFFIX,cnbc.com
DOMAIN-SUFFIX,cnmmb.com
DOMAIN-SUFFIX,colossusssp.com
DOMAIN-SUFFIX,commonwealthproficient.com
DOMAIN-SUFFIX,company-target.com
DOMAIN-SUFFIX,compass-fit.jp
DOMAIN-SUFFIX,confiant-integrations.net
DOMAIN-SUFFIX,connexity.net
DOMAIN-SUFFIX,contextweb.com
DOMAIN-SUFFIX,cootlogix.com
DOMAIN-SUFFIX,corsproxy.io
DOMAIN-SUFFIX,crazyegg.com
DOMAIN-SUFFIX,createjs.com
DOMAIN-SUFFIX,creative-serving.com
DOMAIN-SUFFIX,creativecdn.com
DOMAIN-SUFFIX,criteo.com
DOMAIN-SUFFIX,criteo.net
DOMAIN-SUFFIX,crwdcntrl.net
DOMAIN-SUFFIX,cursor.com
DOMAIN-SUFFIX,cursor.sh
DOMAIN-SUFFIX,cusdis.com
DOMAIN-SUFFIX,cutenico.best
DOMAIN-SUFFIX,dable.io
DOMAIN-SUFFIX,dataseat.com
DOMAIN-SUFFIX,datatables.net
DOMAIN-SUFFIX,db-ip.com
DOMAIN-SUFFIX,dbanotes.net
DOMAIN-SUFFIX,deepintent.com
DOMAIN-SUFFIX,demandbase.com
DOMAIN-SUFFIX,dexi25.com
DOMAIN-SUFFIX,didistatic.com
DOMAIN-SUFFIX,digital-services.solutions
DOMAIN-SUFFIX,divineengine.net
DOMAIN-SUFFIX,doglobal.net
DOMAIN-SUFFIX,dooo.ng
DOMAIN-SUFFIX,dotomi.com
DOMAIN-SUFFIX,doubleverify.com
DOMAIN-SUFFIX,dun.im
DOMAIN-SUFFIX,e-planning.net
DOMAIN-SUFFIX,easy.gov.ltd
DOMAIN-SUFFIX,eclecticlight.co
DOMAIN-SUFFIX,edge.apple
DOMAIN-SUFFIX,edgenat.com
DOMAIN-SUFFIX,eexsync.com
DOMAIN-SUFFIX,eu-1-id5-sync.com
DOMAIN-SUFFIX,everesttech.net
DOMAIN-SUFFIX,evidon.com
DOMAIN-SUFFIX,exchangerate-api.com
DOMAIN-SUFFIX,exelator.com
DOMAIN-SUFFIX,eyeota.net
DOMAIN-SUFFIX,faconhost.com
DOMAIN-SUFFIX,fadb.xyz
DOMAIN-SUFFIX,fanmingming.com
DOMAIN-SUFFIX,fastclick.net
DOMAIN-SUFFIX,fastly-analytics.com
DOMAIN-SUFFIX,faviconkit.com
DOMAIN-SUFFIX,firecore.com
DOMAIN-SUFFIX,flashtalking.com
DOMAIN-SUFFIX,flowercloud.net
DOMAIN-SUFFIX,font.im
DOMAIN-SUFFIX,freegeoip.app
DOMAIN-SUFFIX,ftoutreach.com
DOMAIN-SUFFIX,ftstatic.com
DOMAIN-SUFFIX,g2crowd.com
DOMAIN-SUFFIX,gcorelabs.com
DOMAIN-SUFFIX,genspark.ai
DOMAIN-SUFFIX,geoedge.be
DOMAIN-SUFFIX,geolinks.com
DOMAIN-SUFFIX,getadcdn.com
DOMAIN-SUFFIX,getfavicon.org
DOMAIN-SUFFIX,ggvision.net
DOMAIN-SUFFIX,ghproxy.com
DOMAIN-SUFFIX,gimbal.tech
DOMAIN-SUFFIX,giscus.app
DOMAIN-SUFFIX,glassboxdigital.io
DOMAIN-SUFFIX,globalanalysis.cc
DOMAIN-SUFFIX,gnetwork.me
DOMAIN-SUFFIX,go2app.ai
DOMAIN-SUFFIX,gosquared.com
DOMAIN-SUFFIX,greypanel.com
DOMAIN-SUFFIX,gssprt.jp
DOMAIN-SUFFIX,gubo.org
DOMAIN-SUFFIX,gumgum.com
DOMAIN-SUFFIX,guoshipartners.com
DOMAIN-SUFFIX,h5xxpay.app
DOMAIN-SUFFIX,hackbase.net
DOMAIN-SUFFIX,hadronid.net
DOMAIN-SUFFIX,home-assistant.io
DOMAIN-SUFFIX,hotjar.com
DOMAIN-SUFFIX,hotjar.io
DOMAIN-SUFFIX,hs-analytics.net
DOMAIN-SUFFIX,hs-banner.com
DOMAIN-SUFFIX,hs-scripts.com
DOMAIN-SUFFIX,hsadspixel.net
DOMAIN-SUFFIX,hscollectedforms.net
DOMAIN-SUFFIX,hsforms.com
DOMAIN-SUFFIX,hsforms.net
DOMAIN-SUFFIX,hsleadflows.net
DOMAIN-SUFFIX,hubapi.com
DOMAIN-SUFFIX,hubspot.com
DOMAIN-SUFFIX,hubspotusercontent-na1.net
DOMAIN-SUFFIX,i-meto.com
DOMAIN-SUFFIX,ibruce.info
DOMAIN-SUFFIX,icon.horse
DOMAIN-SUFFIX,iconify.design
DOMAIN-SUFFIX,id5-sync.com
DOMAIN-SUFFIX,iframe.ly
DOMAIN-SUFFIX,illuma-tech.com
DOMAIN-SUFFIX,imjett.ru
DOMAIN-SUFFIX,immtel.co
DOMAIN-SUFFIX,impactradius-go.com
DOMAIN-SUFFIX,impression.link
DOMAIN-SUFFIX,imptracking.com
DOMAIN-SUFFIX,imrworldwide.com
DOMAIN-SUFFIX,indexww.com
DOMAIN-SUFFIX,infolinks.com
DOMAIN-SUFFIX,inhousedsp.com
DOMAIN-SUFFIX,inmarketexchange.com
DOMAIN-SUFFIX,inmobi.com
DOMAIN-SUFFIX,inmobicdn.net
DOMAIN-SUFFIX,inner-active.mobi
DOMAIN-SUFFIX,insent.ai
DOMAIN-SUFFIX,insight-v.ps
DOMAIN-SUFFIX,insightexpressai.com
DOMAIN-SUFFIX,inspi-dsp.com
DOMAIN-SUFFIX,inspidspad.com
DOMAIN-SUFFIX,intentiq.com
DOMAIN-SUFFIX,ip-api.com
DOMAIN-SUFFIX,ip2location.com
DOMAIN-SUFFIX,ipapi.is
DOMAIN-SUFFIX,ipdata.co
DOMAIN-SUFFIX,ipgeolocation.io
DOMAIN-SUFFIX,ipic.vip
DOMAIN-SUFFIX,ipify.org
DOMAIN-SUFFIX,ipinfo.io
DOMAIN-SUFFIX,ipqualityscore.com
DOMAIN-SUFFIX,ipredictive.com
DOMAIN-SUFFIX,ipregistry.co
DOMAIN-SUFFIX,ipstack.com
DOMAIN-SUFFIX,ipwho.is
DOMAIN-SUFFIX,iqm.com
DOMAIN-SUFFIX,iteleserve.com
DOMAIN-SUFFIX,jampp.com
DOMAIN-SUFFIX,jivosite.com
DOMAIN-SUFFIX,jqwenxue.com
DOMAIN-SUFFIX,js-sec.indexww.com
DOMAIN-SUFFIX,k99i.com
DOMAIN-SUFFIX,kargo.com
DOMAIN-SUFFIX,khqrob.lol
DOMAIN-SUFFIX,kivvi.me
DOMAIN-SUFFIX,kochava.com
DOMAIN-SUFFIX,kuaichedao.co
DOMAIN-SUFFIX,kuromis.com
DOMAIN-SUFFIX,lancdn.co
DOMAIN-SUFFIX,launchdarkly.com
DOMAIN-SUFFIX,learnomnifocus.com
DOMAIN-SUFFIX,lemonsqueezy.com
DOMAIN-SUFFIX,lempay.com
DOMAIN-SUFFIX,liadm.com
DOMAIN-SUFFIX,lijit.com
DOMAIN-SUFFIX,linkeless.com
DOMAIN-SUFFIX,lireapp.com
DOMAIN-SUFFIX,lisahost.com
DOMAIN-SUFFIX,livednow.com
DOMAIN-SUFFIX,lkqd.net
DOMAIN-SUFFIX,logcg.com
DOMAIN-SUFFIX,logly.co.jp
DOMAIN-SUFFIX,loli.net
DOMAIN-SUFFIX,loopme.me
DOMAIN-SUFFIX,lowendaff.com
DOMAIN-SUFFIX,lowendtalk.com
DOMAIN-SUFFIX,lr-in-prod.com
DOMAIN-SUFFIX,ltmsphrcl.net
DOMAIN-SUFFIX,macmost.com
DOMAIN-SUFFIX,mathtag.com
DOMAIN-SUFFIX,maxmind.com
DOMAIN-SUFFIX,mcetf.com
DOMAIN-SUFFIX,media.net
DOMAIN-SUFFIX,mediago.io
DOMAIN-SUFFIX,mediarise.io
DOMAIN-SUFFIX,mejiro.io
DOMAIN-SUFFIX,memberful.com
DOMAIN-SUFFIX,mesl.cloud
DOMAIN-SUFFIX,metadata.io
DOMAIN-SUFFIX,mfadsrvr.com
DOMAIN-SUFFIX,mfilterit.net
DOMAIN-SUFFIX,mgid.com
DOMAIN-SUFFIX,midserved.com
DOMAIN-SUFFIX,mij.rip
DOMAIN-SUFFIX,mikuclub.cc
DOMAIN-SUFFIX,mikuclub.fun
DOMAIN-SUFFIX,mikuclub.win
DOMAIN-SUFFIX,mintmobile.com
DOMAIN-SUFFIX,minutemedia-prebid.com
DOMAIN-SUFFIX,missuo.ru
DOMAIN-SUFFIX,mixpo.com
DOMAIN-SUFFIX,mjj.rip
DOMAIN-SUFFIX,mjj.today
DOMAIN-SUFFIX,mktoresp.com
DOMAIN-SUFFIX,mktoutil.com
DOMAIN-SUFFIX,ml314.com
DOMAIN-SUFFIX,mmapiws.com
DOMAIN-SUFFIX,mncdn.com
DOMAIN-SUFFIX,moatads.com
DOMAIN-SUFFIX,mobilefuse.com
DOMAIN-SUFFIX,mookie1.com
DOMAIN-SUFFIX,mp3.zing.vn
DOMAIN-SUFFIX,msftncsi.com
DOMAIN-SUFFIX,mxptint.net
DOMAIN-SUFFIX,mzl.la
DOMAIN-SUFFIX,naixisafe.com
DOMAIN-SUFFIX,nanabianca.it
DOMAIN-SUFFIX,netgear.com
DOMAIN-SUFFIX,newrelic.com
DOMAIN-SUFFIX,nextmillmedia.com
DOMAIN-SUFFIX,nivod.cc
DOMAIN-SUFFIX,nmnm.fun
DOMAIN-SUFFIX,nodeseek.com
DOMAIN-SUFFIX,note.com
DOMAIN-SUFFIX,nr-data.net
DOMAIN-SUFFIX,omappapi.com
DOMAIN-SUFFIX,omnitagjs.com
DOMAIN-SUFFIX,omtrdc.net
DOMAIN-SUFFIX,onaudience.com
DOMAIN-SUFFIX,onesignal.com
DOMAIN-SUFFIX,onetag-sys.com
DOMAIN-SUFFIX,onetechcloud.com
DOMAIN-SUFFIX,onetrust.io
DOMAIN-SUFFIX,onevision.com.tw
DOMAIN-SUFFIX,onthe.io
DOMAIN-SUFFIX,ookla.com
DOMAIN-SUFFIX,opencat.app
DOMAIN-SUFFIX,openwebmp.com
DOMAIN-SUFFIX,openx.net
DOMAIN-SUFFIX,openxcdn.net
DOMAIN-SUFFIX,optable.co
DOMAIN-SUFFIX,orgaorg.com
DOMAIN-SUFFIX,outbrain.com
DOMAIN-SUFFIX,outbrainimg.com
DOMAIN-SUFFIX,oyunfor.com
DOMAIN-SUFFIX,pa-sys.com
DOMAIN-SUFFIX,parsely.com
DOMAIN-SUFFIX,passall.us
DOMAIN-SUFFIX,pcpoxv0614.com
DOMAIN-SUFFIX,pee365.com
DOMAIN-SUFFIX,perfops.io
DOMAIN-SUFFIX,permutive.app
DOMAIN-SUFFIX,permutive.com
DOMAIN-SUFFIX,pghub.io
DOMAIN-SUFFIX,phaibin.me
DOMAIN-SUFFIX,pingid.com
DOMAIN-SUFFIX,pippio.com
DOMAIN-SUFFIX,pixman.io
DOMAIN-SUFFIX,placed.com
DOMAIN-SUFFIX,playground.xyz
DOMAIN-SUFFIX,polarcdn-engine.com
DOMAIN-SUFFIX,polarcdn-pentos.com
DOMAIN-SUFFIX,polarcdn-terrax.com
DOMAIN-SUFFIX,polarcdn.com
DOMAIN-SUFFIX,polyfill.io
DOMAIN-SUFFIX,posthog.com
DOMAIN-SUFFIX,postmarkapp.com
DOMAIN-SUFFIX,postrelease.com
DOMAIN-SUFFIX,printables.com
DOMAIN-SUFFIX,privacymanager.io
DOMAIN-SUFFIX,pro-market.net
DOMAIN-SUFFIX,producthunt.com
DOMAIN-SUFFIX,prreqcroab.icu
DOMAIN-SUFFIX,ptcfc.com
DOMAIN-SUFFIX,pub-f7191f68216549b6b923190821121a54.r2.dev
DOMAIN-SUFFIX,pubmatic.com
DOMAIN-SUFFIX,pubnative.net
DOMAIN-SUFFIX,pxf.io
DOMAIN-SUFFIX,qbk1.com
DOMAIN-SUFFIX,quad9.net
DOMAIN-SUFFIX,quantcount.com
DOMAIN-SUFFIX,quantserve.com
DOMAIN-SUFFIX,quantumdex.io
DOMAIN-SUFFIX,quo.im
DOMAIN-SUFFIX,qvdt3feo.com
DOMAIN-SUFFIX,qwilt.com
DOMAIN-SUFFIX,rebatesme.com
DOMAIN-SUFFIX,redirectlinkway.top
DOMAIN-SUFFIX,remarketstats.com
DOMAIN-SUFFIX,remerge.io
DOMAIN-SUFFIX,researchnow.com
DOMAIN-SUFFIX,resetdigital.co
DOMAIN-SUFFIX,revenuecat.com
DOMAIN-SUFFIX,rezync.com
DOMAIN-SUFFIX,rfchost.com
DOMAIN-SUFFIX,rfihub.com
DOMAIN-SUFFIX,rfihub.net
DOMAIN-SUFFIX,rhebus.io
DOMAIN-SUFFIX,rkdms.com
DOMAIN-SUFFIX,rlcdn.com
DOMAIN-SUFFIX,rnmcnm.com
DOMAIN-SUFFIX,routerlogin.net
DOMAIN-SUFFIX,rsms.me
DOMAIN-SUFFIX,rtbhouse.com
DOMAIN-SUFFIX,rtbsystem.com
DOMAIN-SUFFIX,rtbuniverse.com
DOMAIN-SUFFIX,rubiconproject.com
DOMAIN-SUFFIX,sa.net
DOMAIN-SUFFIX,safeservingcdn.com
DOMAIN-SUFFIX,samplicio.us
DOMAIN-SUFFIX,sascdn.com
DOMAIN-SUFFIX,scorecardresearch.com
DOMAIN-SUFFIX,script.ac
DOMAIN-SUFFIX,scupio.com
DOMAIN-SUFFIX,secureshellfish.app
DOMAIN-SUFFIX,sendinblue.com
DOMAIN-SUFFIX,sensic.net
DOMAIN-SUFFIX,sentry.io
DOMAIN-SUFFIX,serveteck.com
DOMAIN-SUFFIX,serving-data.com
DOMAIN-SUFFIX,sharethis.com
DOMAIN-SUFFIX,sharethrough.com
DOMAIN-SUFFIX,shb-sync.com
DOMAIN-SUFFIX,sift.co
DOMAIN-SUFFIX,simpli.fi
DOMAIN-SUFFIX,singular.net
DOMAIN-SUFFIX,sitescout.com
DOMAIN-SUFFIX,skimresources.com
DOMAIN-SUFFIX,smaato.net
DOMAIN-SUFFIX,smadex.com
DOMAIN-SUFFIX,smadex.net
DOMAIN-SUFFIX,smartadserver.com
DOMAIN-SUFFIX,smilewanted.com
DOMAIN-SUFFIX,sng.link
DOMAIN-SUFFIX,songxwn.com
DOMAIN-SUFFIX,sonobi.com
DOMAIN-SUFFIX,sovrn.com
DOMAIN-SUFFIX,speedtest.net
DOMAIN-SUFFIX,sph.com.sg
DOMAIN-SUFFIX,sphdigital.com
DOMAIN-SUFFIX,sphdigital.com.sg
DOMAIN-SUFFIX,sphlabs.com
DOMAIN-SUFFIX,splunkcloud.com
DOMAIN-SUFFIX,spot.im
DOMAIN-SUFFIX,spotim.market
DOMAIN-SUFFIX,stackadapt.com
DOMAIN-SUFFIX,stacks4libraries.com
DOMAIN-SUFFIX,stacksdiscovery.com
DOMAIN-SUFFIX,stacksinc.net
DOMAIN-SUFFIX,steppark.net
DOMAIN-SUFFIX,stickyadstv.com
DOMAIN-SUFFIX,storygize.net
DOMAIN-SUFFIX,superbed.cc
DOMAIN-SUFFIX,surfsharkdns.com
DOMAIN-SUFFIX,surge-activation.com
DOMAIN-SUFFIX,syndicatedsearch.goog
DOMAIN-SUFFIX,t-mobile.com
DOMAIN-SUFFIX,taboola.com
DOMAIN-SUFFIX,tag.vg
DOMAIN-SUFFIX,tagss04.pro
DOMAIN-SUFFIX,tagsssubscribe.com
DOMAIN-SUFFIX,tapad.com
DOMAIN-SUFFIX,tappx.com
DOMAIN-SUFFIX,teads.tv
DOMAIN-SUFFIX,telemetrydeck.com
DOMAIN-SUFFIX,tenmax.io
DOMAIN-SUFFIX,thekelleys.org.uk
DOMAIN-SUFFIX,tiqcdn.com
DOMAIN-SUFFIX,tk0x1.com
DOMAIN-SUFFIX,tktn.be
DOMAIN-SUFFIX,tkv.one
DOMAIN-SUFFIX,tmmp.io
DOMAIN-SUFFIX,toast.com
DOMAIN-SUFFIX,toimg.xyz
DOMAIN-SUFFIX,topvps.info
DOMAIN-SUFFIX,tpbid.com
DOMAIN-SUFFIX,trackcmp.net
DOMAIN-SUFFIX,trafmag.com
DOMAIN-SUFFIX,trc.taboola.com
DOMAIN-SUFFIX,treasuredata.com
DOMAIN-SUFFIX,tremorhub.com
DOMAIN-SUFFIX,trib.al
DOMAIN-SUFFIX,trustarc.com
DOMAIN-SUFFIX,truste.com
DOMAIN-SUFFIX,tsdtocl.com
DOMAIN-SUFFIX,turn.com
DOMAIN-SUFFIX,tvpixel.com
DOMAIN-SUFFIX,tw93.fun
DOMAIN-SUFFIX,tweesecake.app
DOMAIN-SUFFIX,tynt.com
DOMAIN-SUFFIX,tyyseza.com
DOMAIN-SUFFIX,ultramobile.com
DOMAIN-SUFFIX,umami.dev
DOMAIN-SUFFIX,umami.is
DOMAIN-SUFFIX,undertone.com
DOMAIN-SUFFIX,unionadjs.com
DOMAIN-SUFFIX,unisvg.com
DOMAIN-SUFFIX,unrulymedia.com
DOMAIN-SUFFIX,unt.ag
DOMAIN-SUFFIX,upi.com
DOMAIN-SUFFIX,usbrowserspeed.com
DOMAIN-SUFFIX,usefulcontentsites.com
DOMAIN-SUFFIX,uuuvps.com
DOMAIN-SUFFIX,uuzi.net
DOMAIN-SUFFIX,v.ps
DOMAIN-SUFFIX,v2ray-agent.com
DOMAIN-SUFFIX,v2raysocks.com
DOMAIN-SUFFIX,v5.net
DOMAIN-SUFFIX,vidazoo.com
DOMAIN-SUFFIX,videoamp.com
DOMAIN-SUFFIX,videoplayerhub.com
DOMAIN-SUFFIX,vidoomy.com
DOMAIN-SUFFIX,viglink.com
DOMAIN-SUFFIX,vist.ly
DOMAIN-SUFFIX,vliplatform.com
DOMAIN-SUFFIX,vlitag.com
DOMAIN-SUFFIX,vmiss.com
DOMAIN-SUFFIX,voka1.app
DOMAIN-SUFFIX,vps.hosting
DOMAIN-SUFFIX,vpslog.org
DOMAIN-SUFFIX,vpsxb.top
DOMAIN-SUFFIX,vpsxz.net
DOMAIN-SUFFIX,vrvm.com
DOMAIN-SUFFIX,w55c.net
DOMAIN-SUFFIX,wap.ac
DOMAIN-SUFFIX,wel.one
DOMAIN-SUFFIX,wepc.au
DOMAIN-SUFFIX,weserv.nl
DOMAIN-SUFFIX,wlvpn.com
DOMAIN-SUFFIX,worldssl.net
DOMAIN-SUFFIX,wsimg.com
DOMAIN-SUFFIX,wurfl.io
DOMAIN-SUFFIX,xdaimages.com
DOMAIN-SUFFIX,xpdbk.com
DOMAIN-SUFFIX,xs979.com
DOMAIN-SUFFIX,xtom.com
DOMAIN-SUFFIX,xunihao.net
DOMAIN-SUFFIX,xwyue.com
DOMAIN-SUFFIX,yaoyao.io
DOMAIN-SUFFIX,yellowblue.io
DOMAIN-SUFFIX,yieldmo.com
DOMAIN-SUFFIX,yieldoptimizer.com
DOMAIN-SUFFIX,zabbix.com
DOMAIN-SUFFIX,zaloapp.com
DOMAIN-SUFFIX,zb.sg
DOMAIN-SUFFIX,zemanta.com
DOMAIN-SUFFIX,zeotap.com
DOMAIN-SUFFIX,zgovps.com
DOMAIN-SUFFIX,zi-scripts.com
DOMAIN-SUFFIX,zoominfo.com
DOMAIN-SUFFIX,zorocloud.com
DOMAIN-SUFFIX,zxinc.org
DOMAIN-SUFFIX,zxmx.net
DOMAIN-SUFFIX,atomex.net
DOMAIN-SUFFIX,spotxchange.com
DOMAIN-SUFFIX,bttrack.com
DOMAIN-SUFFIX,aidemsrv.com
DOMAIN-SUFFIX,bidr.io
DOMAIN-SUFFIX,illumin.com
DOMAIN-SUFFIX,visiblemeasures.com
DOMAIN-SUFFIX,ck-ie.com
DOMAIN-SUFFIX,adprime.com
DOMAIN-SUFFIX,acuityplatform.com
DOMAIN-SUFFIX,one-bid.com
DOMAIN-SUFFIX,manico.im
DOMAIN-SUFFIX,trustpilot.com
DOMAIN-SUFFIX,zlidc.net
DOMAIN-SUFFIX,celtra.com
DOMAIN-SUFFIX,attainplatform.io
DOMAIN-SUFFIX,rqtrk.eu
DOMAIN-SUFFIX,peer-39.com
DOMAIN-SUFFIX,puata.info
DOMAIN-SUFFIX,temasekreview.com.sg
DOMAIN-SUFFIX,dolt.cc
DOMAIN-SUFFIX,app-sorteos.com
DOMAIN-SUFFIX,frbsf.org
DOMAIN-SUFFIX,rnengage.com
DOMAIN-SUFFIX,rightnowtech.com
DOMAIN-SUFFIX,atgsvcs.com
DOMAIN-SUFFIX,custhelp.com
DOMAIN-SUFFIX,oracle.com
DOMAIN-SUFFIX,en25.com
DOMAIN-SUFFIX,online-metrix.net
DOMAIN-SUFFIX,askaitools.ai
DOMAIN-SUFFIX,kurun.com
DOMAIN-SUFFIX,mutinyhq.io
DOMAIN-SUFFIX,bounceexchange.com
DOMAIN-SUFFIX,clearbit.com
DOMAIN-SUFFIX,qualified.com
DOMAIN-SUFFIX,contentsquare.net
DOMAIN-SUFFIX,caus.com
DOMAIN-SUFFIX,bizible.com
DOMAIN-SUFFIX,bizibly.com
DOMAIN-SUFFIX,segment.io
DOMAIN-SUFFIX,friendbuy.com
DOMAIN-SUFFIX,mutinycdn.com
DOMAIN-SUFFIX,cookiebot.com
DOMAIN-SUFFIX,impactradius-event.com
DOMAIN-SUFFIX,adxcel-ec2.com
DOMAIN-SUFFIX,cdnbasket.net
DOMAIN-SUFFIX,steelhousemedia.com
DOMAIN-SUFFIX,pstmrk.it
DOMAIN-SUFFIX,bouncex.net
DOMAIN-SUFFIX,flagcdn.com
DOMAIN-SUFFIX,cdnwidget.com
DOMAIN-SUFFIX,prismic.io
DOMAIN-SUFFIX,chilipiper.com
DOMAIN-SUFFIX,58dp.net
DOMAIN-SUFFIX,marketo.net
DOMAIN-SUFFIX,owo.cab
DOMAIN-SUFFIX,restcountries.com
DOMAIN-SUFFIX,sc-static.net
DOMAIN-SUFFIX,libravatar.org
DOMAIN-SUFFIX,collei.net
DOMAIN-SUFFIX,wknd.ai
DOMAIN-SUFFIX,trkn.us
DOMAIN-SUFFIX,moefox.org
DOMAIN-SUFFIX,wawo.wiki
DOMAIN-SUFFIX,wurflcloud.com
DOMAIN-SUFFIX,innovid.com
DOMAIN-SUFFIX,natalie.mu
DOMAIN-SUFFIX,aptv.app
DOMAIN-SUFFIX,pomodoromedia.com
DOMAIN-SUFFIX,adpxrtb.io
DOMAIN-SUFFIX,ixiaocai.net
DOMAIN-SUFFIX,staticfile.org
DOMAIN-SUFFIX,iqzone.com
DOMAIN-SUFFIX,krushmedia.com
DOMAIN-SUFFIX,mobfox.com
DOMAIN-SUFFIX,s3xified.com
DOMAIN-SUFFIX,djamy.net
DOMAIN-SUFFIX,idcoffer.com
DOMAIN-SUFFIX,xtaolabs.com
DOMAIN-SUFFIX,einverne.info
DOMAIN-SUFFIX,kulib.kyoto-u.ac.jp
DOMAIN-SUFFIX,novipnoad.com
DOMAIN-SUFFIX,novipnoad.net
DOMAIN-SUFFIX,dlvr.it
DOMAIN-SUFFIX,vpsxb.cc
DOMAIN-SUFFIX,vpsxxs.com
DOMAIN-SUFFIX,61.life
DOMAIN-SUFFIX,rtactivate.com
DOMAIN-SUFFIX,epg.v1.mk
DOMAIN-SUFFIX,imgdd.com
DOMAIN-SUFFIX,ihainan.me
DOMAIN-SUFFIX,onevcat.com
DOMAIN-SUFFIX,addthis.com
DOMAIN-SUFFIX,saoing.com
DOMAIN-SUFFIX,frostsky.com
DOMAIN-SUFFIX,attentionxyz.com
DOMAIN-SUFFIX,active-agent.com
DOMAIN-SUFFIX,pexels.com
DOMAIN-SUFFIX,ccgateway.net
DOMAIN-SUFFIX,tpmn.co.kr
DOMAIN-SUFFIX,tpmn.io
DOMAIN-SUFFIX,clmbtech.com
DOMAIN-SUFFIX,emxdgt.com
DOMAIN-SUFFIX,mediavine.com
DOMAIN-SUFFIX,prntscr.com
DOMAIN-SUFFIX,mediawallahscript.com
DOMAIN-SUFFIX,cdn-net.com
DOMAIN-SUFFIX,revcontent.com
DOMAIN-SUFFIX,arkoselabs.com
DOMAIN-SUFFIX,wa-lang.org
DOMAIN-SUFFIX,payten.com.tr
DOMAIN-SUFFIX,iyzipay.com
DOMAIN-SUFFIX,adingo.jp
DOMAIN-SUFFIX,iyzico.com
DOMAIN-SUFFIX,dmxleo.com
DOMAIN-SUFFIX,isbank.com.tr
DOMAIN-SUFFIX,paytr.com
DOMAIN-SUFFIX,innity.com
DOMAIN-SUFFIX,innity.net
DOMAIN-SUFFIX,kaix.in
DOMAIN-SUFFIX,uuphy.com
DOMAIN-SUFFIX,crisp.help
DOMAIN-SUFFIX,dropoverapp.com
DOMAIN-SUFFIX,chimpstatic.com
DOMAIN-SUFFIX,defybrick.com
DOMAIN-SUFFIX,hanyang.wtf
DOMAIN-SUFFIX,streamtheworld.com
DOMAIN-SUFFIX,substackcdn.com
DOMAIN-SUFFIX,krxd.net
DOMAIN-SUFFIX,geistm.com
DOMAIN-SUFFIX,jjbangbang.com
DOMAIN-SUFFIX,kingwayer.com
DOMAIN-SUFFIX,cdnxyy.com
DOMAIN-SUFFIX,stickytimers.app
DOMAIN-SUFFIX,ni2zp.top
DOMAIN-SUFFIX,speed4card.com
DOMAIN-SUFFIX,m123.org
DOMAIN-SUFFIX,dpqklv.com
DOMAIN-SUFFIX,ossk.cc
DOMAIN-SUFFIX,adxpremium.services
DOMAIN-SUFFIX,warkseza.com
DOMAIN-SUFFIX,temu.com
DOMAIN-SUFFIX,bpc.dev
DOMAIN-SUFFIX,akkocloud.com
DOMAIN-SUFFIX,jsqsa.top
DOMAIN-SUFFIX,catcat.blog
DOMAIN-SUFFIX,lutaonan.com
DOMAIN-SUFFIX,adsmoloco.com
DOMAIN-SUFFIX,nordot.app
DOMAIN-SUFFIX,tailwindui.com
DOMAIN-SUFFIX,raspberrypi.com
DOMAIN-SUFFIX,launtel.net.au
DOMAIN-SUFFIX,666clouds.com
DOMAIN-SUFFIX,esquirehk.com
DOMAIN-SUFFIX,1point3acres.com
DOMAIN-SUFFIX,coffeebox.tw
DOMAIN-SUFFIX,futurecdn.net
DOMAIN-SUFFIX,framer.com
DOMAIN-SUFFIX,framerusercontent.com
DOMAIN-SUFFIX,steampowered.com
DOMAIN-SUFFIX,natgeofe.com
DOMAIN-SUFFIX,media.gq.com.tw
DOMAIN-SUFFIX,fyber.com
DOMAIN-SUFFIX,the-decoder.com
DOMAIN-SUFFIX,modernretail.co
DOMAIN-SUFFIX,klaviyo.com
DOMAIN-SUFFIX,kwipped.com
DOMAIN-SUFFIX,rechargeadapter.com
DOMAIN-SUFFIX,approvepayments.com
DOMAIN-SUFFIX,bigcommerce.com
DOMAIN-SUFFIX,sentry-cdn.com
DOMAIN-SUFFIX,butfirstcoffee.nz
DOMAIN-SUFFIX,trackjs.com
DOMAIN-SUFFIX,attn.tv
DOMAIN-SUFFIX,nosto.com
DOMAIN-SUFFIX,attentivemobile.com
DOMAIN-SUFFIX,iyideng.org
DOMAIN-SUFFIX,yinpinjie.com
DOMAIN-SUFFIX,nommagazine.com
DOMAIN-SUFFIX,yotpo.com
DOMAIN-SUFFIX,prima-coffee.com
DOMAIN-SUFFIX,mybigcommerce.com
DOMAIN-SUFFIX,helloextend.com
DOMAIN-SUFFIX,lacunads.com
DOMAIN-SUFFIX,metricool.com
DOMAIN-SUFFIX,wada-ama.org
DOMAIN-SUFFIX,xtrojan.org
DOMAIN-SUFFIX,eppo.cloud
DOMAIN-SUFFIX,cleanshot.cloud
DOMAIN-SUFFIX,panjinbo.com
DOMAIN-SUFFIX,yylx.tech
DOMAIN-SUFFIX,hezu.v1.mk
DOMAIN-SUFFIX,233444.xyz
DOMAIN-SUFFIX,quail.ink
DOMAIN-SUFFIX,tvzb.com
DOMAIN-SUFFIX,kyivindependent.com
DOMAIN-SUFFIX,imgimg.cc
DOMAIN-SUFFIX,pressablecdn.com
DOMAIN-SUFFIX,restofworld.org
DOMAIN-SUFFIX,skyreels.ai
DOMAIN-SUFFIX,a16z.com
DOMAIN-SUFFIX,hhisgg.xyz
DOMAIN-SUFFIX,pub.com
DOMAIN-SUFFIX,locimg.com
DOMAIN-SUFFIX,cnswift.org
DOMAIN-SUFFIX,cdt.media
DOMAIN-SUFFIX,sitecorecloud.io
DOMAIN-SUFFIX,trendmd.com
DOMAIN-SUFFIX,survata.com
DOMAIN-SUFFIX,upwave.com
DOMAIN-SUFFIX,sixtynet.net
DOMAIN-SUFFIX,termly.io
DOMAIN-SUFFIX,xuanyuanhuangdi.org
DOMAIN-SUFFIX,typlog.com
DOMAIN-SUFFIX,imgbox.com
DOMAIN-SUFFIX,tupian.li
DOMAIN-SUFFIX,izt6.com
DOMAIN-SUFFIX,gao.ee
DOMAIN-SUFFIX,laoda.de
DOMAIN-SUFFIX,v2money.net
DOMAIN-SUFFIX,loll.cc
DOMAIN-SUFFIX,adm-services.goog
DOMAIN-SUFFIX,meetupstatic.com
DOMAIN-SUFFIX,yrl.ee
DOMAIN-SUFFIX,openweb.bid
DOMAIN-SUFFIX,spiritlhl.net
DOMAIN-SUFFIX,getrockerbox.com
DOMAIN-SUFFIX,sync.ex.co
DOMAIN-SUFFIX,springserve.com
DOMAIN-SUFFIX,ialue.com
DOMAIN-SUFFIX,pointmediatracker.com
DOMAIN-SUFFIX,blisspointmedia.com
DOMAIN-SUFFIX,website-files.com
DOMAIN-SUFFIX,kejiwanjia.net
DOMAIN-SUFFIX,isagood.day
DOMAIN-SUFFIX,richaudience.com
DOMAIN-SUFFIX,bemyeyes.com
DOMAIN-SUFFIX,coinlive.com
DOMAIN-SUFFIX,steamstatic.com
DOMAIN-SUFFIX,paulgraham.com
DOMAIN-SUFFIX,brewpot.co
DOMAIN-SUFFIX,ahu.moe
DOMAIN-SUFFIX,iecho.cc
DOMAIN-SUFFIX,straitstimes.com.sg
DOMAIN-SUFFIX,estk.me
DOMAIN-SUFFIX,thumbsnap.com
DOMAIN-SUFFIX,onezm.com
DOMAIN-SUFFIX,dvo.ru
DOMAIN-SUFFIX,britannica.com
DOMAIN-SUFFIX,gardenerspath.com
DOMAIN-SUFFIX,bhg.com
DOMAIN-SUFFIX,gardendesign.com
DOMAIN-SUFFIX,thespruce.com
DOMAIN-SUFFIX,affine.pro
DOMAIN-SUFFIX,jamloop.net
DOMAIN-SUFFIX,affineassets.com
DOMAIN-SUFFIX,affine.run
DOMAIN-SUFFIX,alue.life
DOMAIN-SUFFIX,qweather.net
DOMAIN-SUFFIX,bichsexs.com
DOMAIN-SUFFIX,follow.is
DOMAIN-SUFFIX,brightspotcdn.com
DOMAIN-SUFFIX,ensighten.com
DOMAIN-SUFFIX,stbuttons.click
DOMAIN-SUFFIX,mayoclinic.org
DOMAIN-SUFFIX,dengagecdn.com
DOMAIN-SUFFIX,dengage.com
DOMAIN-SUFFIX,reeder.app
DOMAIN-SUFFIX,medallia.com
DOMAIN-SUFFIX,go-mpulse.net
DOMAIN-SUFFIX,stardots.ink
DOMAIN-SUFFIX,1111hk.com
DOMAIN-SUFFIX,healthnews.com.tw
DOMAIN-SUFFIX,kaseisyoji.com
DOMAIN-SUFFIX,sanalakpos.com
DOMAIN-SUFFIX,yuzhi.tech
DOMAIN-SUFFIX,imgdrop.io
DOMAIN-SUFFIX,wb1cjv.nl
DOMAIN-SUFFIX,adsdog.ai
DOMAIN-SUFFIX,jivox.com
DOMAIN-SUFFIX,esonwong.com
DOMAIN-SUFFIX,serving-sys.com
DOMAIN-SUFFIX,decibelinsight.net
DOMAIN-SUFFIX,cfigroup.com
DOMAIN-SUFFIX,digitalgov.gov
DOMAIN-SUFFIX,wzznft.com
DOMAIN-SUFFIX,qualtrics.com
DOMAIN-SUFFIX,qzuep.top
DOMAIN-SUFFIX,raphaelmedical.com.tw
DOMAIN-SUFFIX,invocacdn.com
DOMAIN-SUFFIX,blismedia.com
DOMAIN-SUFFIX,kampyle.com
DOMAIN-SUFFIX,smilerx.com.tw
DOMAIN-SUFFIX,911tg3rs.com
DOMAIN-SUFFIX,livekit.cloud
DOMAIN-SUFFIX,acexedge.com
DOMAIN-SUFFIX,cdn-cookieyes.com
DOMAIN-SUFFIX,cookieyes.com
DOMAIN-SUFFIX,nature.com
DOMAIN-SUFFIX,plausible.io
DOMAIN-SUFFIX,tq-tungsten.com
DOMAIN-SUFFIX,imgai.ai
DOMAIN-SUFFIX,vcvit.me
DOMAIN-SUFFIX,gdppseza.com
DOMAIN-SUFFIX,ccyp.com
DOMAIN-SUFFIX,xxsmtz1.com
DOMAIN-SUFFIX,docsbot.ai
DOMAIN-SUFFIX,undercurrentss.com
DOMAIN-SUFFIX,tantsissa.com
DOMAIN-SUFFIX,liftoff-creatives.io
DOMAIN-SUFFIX,cheqzone.com
DOMAIN-SUFFIX,pix.pub
DOMAIN-SUFFIX,titanium-software.fr
DOMAIN-SUFFIX,dvd.moe
DOMAIN-SUFFIX,dvd.chat
DOMAIN-SUFFIX,yojigen.tech
DOMAIN-SUFFIX,ismcdn.jp
DOMAIN-SUFFIX,gendai.media
DOMAIN-SUFFIX,troz.net
DOMAIN-SUFFIX,b2c.com
DOMAIN-SUFFIX,halo.do
DOMAIN-SUFFIX,cnyysexs.com
DOMAIN-SUFFIX,futoon.org
DOMAIN-SUFFIX,z4a.net
DOMAIN-SUFFIX,slax.com
DOMAIN-SUFFIX,cqd4n.top
DOMAIN-SUFFIX,anythinktech.com
DOMAIN-SUFFIX,cxense.com
DOMAIN-SUFFIX,privacy-mgmt.com
DOMAIN-SUFFIX,iphonemod.net
DOMAIN-SUFFIX,jmap.io
DOMAIN-SUFFIX,datadome.co
DOMAIN-SUFFIX,zqtk.net
DOMAIN-SUFFIX,cleanshot.com
DOMAIN-SUFFIX,decider.com
DOMAIN-SUFFIX,pagesix.com
DOMAIN-SUFFIX,penews.com
DOMAIN-SUFFIX,newscgp.com
DOMAIN-SUFFIX,dianomi.com
DOMAIN-SUFFIX,ncaudienceexchange.com
DOMAIN-SUFFIX,central-world.org
DOMAIN-SUFFIX,anymind360.com
DOMAIN-SUFFIX,uidapi.com
DOMAIN-SUFFIX,smoe.top
DOMAIN-SUFFIX,claw.cloud
DOMAIN-SUFFIX,clawcloudsingaporeprivatelimited.sjv.io
DOMAIN-SUFFIX,digvps.com
DOMAIN-SUFFIX,pixman.cloud
DOMAIN-SUFFIX,kelee.one
DOMAIN-SUFFIX,smartyads.com
DOMAIN-SUFFIX,macked.app
DOMAIN-SUFFIX,avplayer.com
DOMAIN-SUFFIX,ggff.net
DOMAIN-SUFFIX,railway.app
DOMAIN-SUFFIX,rssforever.com
DOMAIN-SUFFIX,playstream.media
DOMAIN-SUFFIX,tabby.sh
DOMAIN-SUFFIX,diygod.dev
DOMAIN-SUFFIX,vidgyor.com
DOMAIN-SUFFIX,vpsradar.com
DOMAIN-SUFFIX,dmit.io
DOMAIN-SUFFIX,gafei.com
DOMAIN-SUFFIX,vkvm.info
DOMAIN-SUFFIX,zeabur.com
DOMAIN-SUFFIX,syyn.pw
DOMAIN-SUFFIX,flaticon.com
DOMAIN-SUFFIX,deovr.com
DOMAIN-SUFFIX,fonts.cat.net
DOMAIN-SUFFIX,synn.cc
DOMAIN-SUFFIX,imagedelivery.net
DOMAIN-SUFFIX,cubecloud.net
DOMAIN-SUFFIX,wxj.cn
DOMAIN-SUFFIX,nginxui.com
DOMAIN-SUFFIX,anyfeeder.com
DOMAIN-SUFFIX,moyu.im
DOMAIN-SUFFIX,vtrk.dv.tech
DOMAIN-SUFFIX,admaster.cc
DOMAIN-SUFFIX,bblmw.com
DOMAIN-SUFFIX,makerworld.com
DOMAIN-SUFFIX,naiyous.com
DOMAIN-SUFFIX,dadigua.men
DOMAIN-SUFFIX,ebxcdn.com
DOMAIN-SUFFIX,gizmodo.com
DOMAIN-SUFFIX,felo.me
DOMAIN-SUFFIX,xiaoz.org
DOMAIN-SUFFIX,img2ipfs.com
DOMAIN-SUFFIX,padsquad.com
DOMAIN-SUFFIX,visualmax.com
DOMAIN-SUFFIX,copper6.com
DOMAIN-SUFFIX,apis-padsquad.com
DOMAIN-SUFFIX,g60.net
DOMAIN-SUFFIX,imtwjwoasak.com
DOMAIN-SUFFIX,ioopsefv.com
DOMAIN-SUFFIX,williams-sonoma.com
DOMAIN-SUFFIX,crcldu.com
DOMAIN-SUFFIX,rvikjd.com
DOMAIN-SUFFIX,qingr.moe
DOMAIN-SUFFIX,vistarsagency.com
DOMAIN-SUFFIX,thisisdax.com
DOMAIN-SUFFIX,adtheorent.com
DOMAIN-SUFFIX,ispot.tv
DOMAIN-SUFFIX,applefans.net
DOMAIN-SUFFIX,hk01.com
DOMAIN-SUFFIX,chinadigitaltimes.net
DOMAIN-SUFFIX,feedx.net
DOMAIN-SUFFIX,skk.moe
DOMAIN-SUFFIX,cloudflareinsights.com
DOMAIN-SUFFIX,9to5mac.com
DOMAIN-SUFFIX,9to5toys.com
DOMAIN-SUFFIX,amazon-adsystem.com
DOMAIN-SUFFIX,demdex.net
DOMAIN-SUFFIX,decart.ai
DOMAIN-SUFFIX,macrumors.com
DOMAIN-SUFFIX,rt.com
DOMAIN-SUFFIX,zen-browser.app
DOMAIN-SUFFIX,1zpresso.coffee
DOMAIN-SUFFIX,ysxue.net
DOMAIN-SUFFIX,bbc.in
DOMAIN-SUFFIX,store-assets.com
DOMAIN-SUFFIX,momoshop.com.tw
DOMAIN-SUFFIX,zpaeng.com
DOMAIN-SUFFIX,turncdn.com
DOMAIN-SUFFIX,chanchao.com.tw
DOMAIN-SUFFIX,simba.sg
DOMAIN-SUFFIX,im-apps.net
DOMAIN-SUFFIX,iwillvote.com
DOMAIN-SUFFIX,nxtrace.org
DOMAIN-SUFFIX,heptasky.com
DOMAIN-SUFFIX,codacy.com
DOMAIN-SUFFIX,circleci.com
DOMAIN-SUFFIX,containrrr.dev
DOMAIN-SUFFIX,goreportcard.com
DOMAIN-SUFFIX,jiml.ee
DOMAIN-SUFFIX,wiki-power.com
DOMAIN-SUFFIX,imaegoo.com
DOMAIN-SUFFIX,razinj.dev
DOMAIN-SUFFIX,vercel-insights.com
DOMAIN-SUFFIX,dsuper.xyz
DOMAIN-SUFFIX,ghp.ci
DOMAIN-SUFFIX,harish2k01.in
DOMAIN-SUFFIX,pocketcasts.com
DOMAIN-SUFFIX,sentinelone.com
DOMAIN-SUFFIX,intercom.io
DOMAIN-SUFFIX,huo.me
DOMAIN-SUFFIX,stripe.com
DOMAIN-SUFFIX,stripe.network
DOMAIN-SUFFIX,arlxn.top
DOMAIN-SUFFIX,0x0.ooo
DOMAIN-SUFFIX,orangevps.com
DOMAIN-SUFFIX,tawk.to
DOMAIN-SUFFIX,claudeusercontent.com
"""

RULE_OPTIONS = {"extended-matching", "no-resolve"}
IP_RULE_PREFIXES = ("IP-CIDR,", "IP-CIDR6,", "IP-ASN,")


def fetch_text(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": "xiaopan007-surge-global-builder"})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read().decode("utf-8")


def normalize_rule(raw_line: str) -> str | None:
    line = raw_line.strip()
    if not line or line.startswith("#"):
        return None

    if "," not in line:
        value = line.lower()
        if value.startswith("."):
            return f"DOMAIN-SUFFIX,{value[1:]}"
        return f"DOMAIN,{value}"

    parts = [part.strip() for part in line.split(",")]
    while parts and parts[-1].lower() in RULE_OPTIONS:
        parts.pop()

    if len(parts) < 2:
        return None

    parts[0] = parts[0].upper()
    if parts[0] in {"DOMAIN", "DOMAIN-SUFFIX", "DOMAIN-KEYWORD"}:
        parts[1] = parts[1].lower().lstrip(".")

    line = ",".join(parts)
    if line.startswith(IP_RULE_PREFIXES) and not line.lower().endswith(",no-resolve"):
        line = f"{line},no-resolve"
    return line


def add_rules(text: str, seen: set[str], rules: list[str]) -> int:
    count = 0
    for raw_line in text.splitlines():
        rule = normalize_rule(raw_line)
        if rule and rule not in seen:
            seen.add(rule)
            rules.append(rule)
            count += 1
    return count


def main() -> None:
    seen: set[str] = set()
    rules: list[str] = []

    add_rules(fetch_text(BLACKMATRIX_GLOBAL_URL), seen, rules)
    add_rules(GLOBAL_EXTENSION_RULES, seen, rules)

    OUTPUT.write_text("\n".join([f"# 规则数量: {len(rules)}"] + rules) + "\n")


if __name__ == "__main__":
    main()
